### PR TITLE
Added support for groups

### PR DESCRIPTION
**Pull request by masihyeganeh**
For #21 I wrote this.
Please check it. It's working but you may rewrite it better.
I need groups, so please add it.

Thanks

### CODE REVIEW

**Comment by Evgenus** [comment]
too much changes. I will need to reapply diff regardless to line endings.

**Comment by masihyeganeh** [comment]
Fine by me. Just need this change in pip version.
I'll be grateful if you do this

**Comment by masihyeganeh** [comment]
Ok, I fixed my pull  request. it is now more clear.
I don't know if this repository is abandoned or not, but if it is not, please merge my commit and update pip version.
I need it in my project.

I think you could do it better, but it's just doing the job without breaking any other thing.

Thanks in advance.

**Comment by masihyeganeh** [comment]
Can you please merge my PR? or let me publish this as a new pypi package.
I'm using this in my project and I need it.

Thanks

**Comment by masihyeganeh** [comment]
Hi.
I know that this project is abandoned, but will you please take a look at my PR?
I'm using it since a year ago and everything is fine.
I just need it to be fetched by PIP without modifying it's files manually.
I appreciate you taking the time to reading and maybe merging it

**Pull request merged**
